### ISSUE TITLE
SDF does not work in standalone build

### ISSUE THREAD

**Issue by moffatjason** [aman-tiwari/MeshToSDF#1]
When i run the demo scene in a build i get no errors its like the SDF is not created.  Can it be modified so that the texture is written to a file not at runtime?

**Comment by aman-tiwari** [comment]
Could you attach a simple scene to reproduce this issue?

**Comment by moffatjason** [comment]
I didnt change the Demo scene provided, simply built it for Windows.


1. Create HDRP project (Unity 2018.3.6 or 2018.3.8 releases)
2. Package Manager import VFX Graph (4.10.0-preview)
3. Package Manager update HDRP (4.10.0-preview)
4. Import the MeshToSDF package.
5. Build Standalone.
6. Run.
7. Particle effect appears briefly then disappears.  Slice View shows white.

**Comment by DrBlort** [comment]
Change the ID assignations  from OnValidate() to Start() or Awake(). 

OnValidate is only called in the Editor (Of course, I realized that after about 4 hours of trying to understand and debugging the script and the compute shaders themselves, hah).
Seems that all the IDs were 0 in the build, so it kept calling the wrong kernel.

Things like that are why it's necessary to test with an actual build from time to time :)

**Comment by aman-tiwari** [comment]
Thanks! Sorry for the oversight, fixed in latest push!
