### ISSUE TITLE
Change Resolution for x,y,z individually

### ISSUE THREAD

**Issue by Podden** [aman-tiwari/MeshToSDF#4]
Would be awesome for extruded Text cause this is usually not a good fit for a cube.

**Comment by aman-tiwari** [comment]
Feel free to make a pull request for this. Most likely the only thing that'll need to change is doing the scaling in 3 dims instead of just using the cube side and bounds checking in the JFA compute shader (keep the current version as an optimized one to be used on power of 2 cubes)
